In [1]:
import numpy as np

In [2]:
a=np.array([30,50,20,40,60])
a

array([30, 50, 20, 40, 60])

In [3]:
np.mean(a)

40.0

In [4]:
np.median(a)

40.0

In [5]:
b=np.array([343,556,788,22,55,78,90,20,10,14])
np.mean(b)

197.6

In [6]:
np.median(b)

66.5

In [7]:
c= np.array([[20,40,30],[70,50,90]])
c

array([[20, 40, 30],
       [70, 50, 90]])

In [8]:
np.mean(c)


50.0

In [9]:
np.mean(c,axis=0)

array([45., 45., 60.])

In [10]:
np.mean(c,axis=1)

array([30., 70.])

In [11]:
np.median(c)

45.0

In [12]:
np.median(c,axis=0)

array([45., 45., 60.])

In [13]:
np.median(c,axis=1)

array([30., 70.])

In [17]:
#standard deviation
a=np.array([20,30,40,70,60])
a


array([20, 30, 40, 70, 60])

In [18]:
b=np.array([343,656,211,422,22,77,99,21])
b


array([343, 656, 211, 422,  22,  77,  99,  21])

In [21]:
c=np.array([[53,72,99,61],[27,63,88,22]])
c           

array([[53, 72, 99, 61],
       [27, 63, 88, 22]])

In [22]:
np.var(a)

344.0

In [23]:
np.var(b)

44871.234375

In [24]:
np.var(c)

629.734375

In [25]:
np.std(a)

18.547236990991408

In [30]:
round(np.std(a),1)

18.5

In [31]:
np.std(b)

211.82831344038973

In [33]:
round(np.std(b))

212

In [34]:
np.std(c)

25.094508861501954

In [35]:
round(np.std(c),2)

25.09

In [36]:
p=np.std(c)
p

25.094508861501954

In [37]:
round(p,1)

25.1

In [38]:
c

array([[53, 72, 99, 61],
       [27, 63, 88, 22]])

In [39]:
np.var(c,axis=0)#ROWS

array([169.  ,  20.25,  30.25, 380.25])

In [40]:
np.var(c,axis=1)#columns

array([302.1875, 731.5   ])

In [41]:
np.min(a)

20

In [43]:
np.max(a)

70

In [42]:
np.max(b)

656

In [44]:
np.min(b)

21

In [45]:
myrange=np.max(a)-np.min(a)

In [46]:
myrange

50

In [47]:
myrange=np.max(b)-np.min(b)

In [48]:
myrange

635

In [49]:
d=np.array([[23,45,90,34],[65,33,21,78],[90,45,89,66]])
d    

array([[23, 45, 90, 34],
       [65, 33, 21, 78],
       [90, 45, 89, 66]])

In [50]:
np.var(d)

635.9097222222222

In [52]:
round(np.var(d),1)

635.9

In [53]:
np.var(d,axis=0)

array([ 764.22222222,   32.        , 1042.88888889,  344.88888889])

In [54]:
np.var(d,axis=1)

array([648.5   , 534.1875, 344.25  ])

In [55]:
np.std(d)

25.217250488945503

In [56]:
np.std(d,axis=0)

array([27.64456949,  5.65685425, 32.29379025, 18.57118437])

In [57]:
np.std(d,axis=1)

array([25.46566316, 23.11249662, 18.55397532])